// <auto-generated />
namespace IT_Proekt_173032.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class novaMigracija : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(novaMigracija));
        
        string IMigrationMetadata.Id
        {
            get { return "201910060920316_novaMigracija"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
